// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlrsfqruzgbpziaflryl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJscnNmcXJ1emdicHppYWZscnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMjQwNzEsImV4cCI6MjA1MzcwMDA3MX0.xLHc2wjkuXq-PnYVSloc1RIMvXSl90lhAyfGfmjyRzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);